### ISSUE TITLE
Về mục đích dữ đoán lương cầu thủ? và một vài góp ý + thắc mắc

### ISSUE THREAD

**Issue by hmhuan** [linanthon/KHDL_DA#1]
Như tiêu đề thì mục đích nhóm bạn dự đoán lương các tuyển thủ để làm gì (ai cần biết điều này? mang lợi ích gì không?).
Trong thể thao nói chung qua các mùa thường có vụ chuyển nhượng (giống nhảy việc), điều này ảnh hưởng nhiều đến mức lương của họ nhưng hình như là sẽ rất khó để dự đoán, vậy nhóm bạn có hướng giải quyết ra sao

**Comment by linanthon** [comment]
Chào bạn, bài làm của tụi mình là dự đoán base salary (lương cơ bản) dựa theo khả năng của tuyển thủ trên sân đấu nên tụi mình sẽ không xét đến những điều khoản đặc biệt trong hợp đồng của từng tuyển thủ (điều khoản trung thành, điều khoản tăng lương theo thành tích, ...) và dự định tương lai của họ.
Mục đích bài toán giúp chính tuyển thủ và ban lãnh đạo của đội bóng có thể dễ dàng bàn mức lương cơ bản hơn.

**Comment by KienTrann** [comment]
@ Nhóm 7:
- Mình thấy trong trang web về lương có cả lương của năm 2020, 2021, ... Tại sao vậy em?
- Nhóm em muốn "dự đoán lương của các cầu thủ bóng rổ cho mùa tiếp theo dựa trên chỉ số của họ trong mùa này". Vậy thì mình nghĩ tập huấn luyện nên gồm chỉ số của mùa t và lương của mùa t+1, đúng không nhỉ?

**Comment by linanthon** [comment]
Chào thầy,
Câu 1: Lương 2020, 2021 của trang web đó là lương tăng theo năm của tuyển thủ nếu tiếp tục giữ được phong độ và chơi cho đội bóng.
Câu 2: Dạ đúng rồi thầy, chúng em lấy thông số tuyển thủ của 2018-19 và lương của 2019-20.
