### ISSUE TITLE
góp ý: scale salary và model khác?

### ISSUE THREAD

**Issue by hmhuan** [linanthon/KHDL_DA#2]
- bên nhóm tui cũng làm regression, lúc đầu để nguyên giá trị của price đơn vị ($) thì nó cũng ra kết quả không được tốt, nhưng khi scale về đơn vị (nghìn $) thì kết quả khả quan hơn. Nhóm ông thử scale salary về (triệu $ hay trăm nghìn $) thử xem sao (hiện tại ở mức nghìn $ phải không?).

- ngoài ra, nhóm ông có thể thử build model với RandomForestRegressor, t thấy no cho kết quả khá tốt.

**Comment by TrietNguyen-Byte** [comment]
Cảm ơn nhóm bạn đã góp ý nha, tụi mình sẽ thử các cách trên
